namespace codingfreaks.obscene.Logic.WinApi.Models
{
    /// <summary>
    /// Transports information about a window generated by the Windows API.
    /// </summary>
    /// <remarks>
    /// This type is immutable.
    /// </remarks>
    public struct WindowInformation
    {
        #region constructors and destructors

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="handle">The handle to identify the created window.</param>
        /// <param name="className">The registerd class Name of the window.</param>
        /// <param name="identifier">The identifier of the window registration used during generation.</param>
        public WindowInformation(IntPtr handle, IntPtr className, string identifier)
        {
            Handle = handle;
            ClassName = className;
            Identifier = identifier;
        }

        #endregion

        #region properties

        /// <summary>
        /// The handle to identify the created window.
        /// </summary>
        public IntPtr Handle { get; }

        /// <summary>
        /// The registerd class Name of the window.
        /// </summary>
        public nint ClassName { get; }

        /// <summary>
        /// The identifier of the window registration used during generation.
        /// </summary>
        public string Identifier { get; set; }

        #endregion
    }
}